@baseUrl = http://localhost:3000

### Get all questions
GET {{baseUrl}}/questions

### Get all questions with multiple filters
GET {{baseUrl}}/questions?difficulty=senior&topic=Architecture,Microservices

### Get a specific question by ID
GET {{baseUrl}}/questions/3

### Get a random question
GET {{baseUrl}}/questions/random

### Submit a correct answer
POST {{baseUrl}}/answers/8
Content-Type: application/json

{
  "answer": "Ensures token has not been tampered with."
}

### Swagger API Documentation
GET {{baseUrl}}/api
